### ISSUE TITLE
move_storage() not asynchronous when low IO happens

### ISSUE THREAD

**Issue by murder** [rakshasa/libtorrent#106]
This happens when I have a destination with low IO throughput

Eg: My setup is basically:

- Download to SSD mountpoint (/data/fast/incomplete)
- Once finished, move to low rpm HDD big storage (/data/slow/new)

So, when this process happens, everything that the client (libtorrent) is doing is stalled and waits for the copy to happens.

Reproduce:

1. Add various downloads and start them (around 10gb+ size)
2. Move any finished downloads to a low IO mountpoint (eg: USB 2.0 External HDD)
3. Notice the non-finished downloads stall

Related to move_storage() - ​http://www.rasterbar.com/products/libtorrent/manual.html

**move_storage()**

```
void move_storage(std::string const& save_path) const;
void move_storage(std::wstring const& save_path) const;

```

> Moves the file(s) that this torrent are currently seeding from or downloading to. If the given save_path is not located on the same drive as the original save path, The files will be copied to the new drive and removed from their original location. **This will block all other disk IO**, and other torrents download and upload rates may drop while copying the file.

This affects various client implementations that rely on libtorrent.
Can't this be fixed (featured)?

**Comment by rakshasa** [comment]
Wrong library.
