### ISSUE TITLE
Home page shows standard "Apache2 Ubuntu Default Page", and "/downloads" gives a 403?

### ISSUE THREAD

**Issue by jf** [rakshasa/libtorrent#107]
sorry to be bringing up this issue here, but since the description of the project over at GitHub does point to this host/page (http://rtorrent.net/downloads/), I figured I'd open up an issue here.

**Comment by rakshasa** [comment]
Fixed.

**Comment by jf** [comment]
Thanks. There are actually 2 issues in here, just to be clear. Thanks for fixing "/downloads". Is there any reason for not bothering with the home page (rtorrent.net)?
