### ISSUE TITLE
Adding ipv6 support

### ISSUE THREAD

**Issue by chros73** [rakshasa/libtorrent#111]
@rakshasa : I know you will start working on this and I found a solution that based on your ipv6 branch (I haven't gone through it), maybe it can be helping you: [libtorrent-ipv6-patches](https://github.com/JohnFlowerful/libtorrent-ipv6-patches) , [rtorrent-ipv6-patches](https://github.com/JohnFlowerful/rtorrent-ipv6-patches)

**Comment by chros73** [comment]
Since, I'm using those patches for 2 weeks now, just one thought popped in my mind:
`network.bind_address.set` in rtorrent config and in libtorrent [torrent/connection_manager.cc](https://github.com/rakshasa/libtorrent/blob/5a3bea6602348caaabdb7a500717658137c9df2c/src/torrent/connection_manager.cc#L142) should be modified to be able to handle multiple ip's/interfaces.

**Comment by rakshasa** [comment]
When I got my vagrant [test environment](https://github.com/rakshasa/rtorrent-vagrant) ready I'll look into IPv6.

**Comment by rakshasa** [comment]
Merged.
