### ISSUE TITLE
IPv6 bugs

### ISSUE THREAD

**Issue by chros73** [rakshasa/libtorrent#114]
First of all, thanks for adding ipv6 support! (#111)
I just quickly tried it out, and I came across the following problems (both were existed with the previosly mentioned patches):

A. Can't connect to udp trackers, error message: `Tracker: [Could not open UDP socket.]`
Used config: note, that `network.bind_address` is disabled to be able to use both ipv4 AND ipv6.
```
#network.bind_address.set = 192.168.1.6
schedule2 = ip_tick, 0, 1800, network.local_address.set=somehost.no-ip.org
network.port_range.set = 60367-60367
trackers.use_udp.set = true
dht.mode.set = auto
dht.port.set = 60378
```
Is the missing `network.bind_address` option the problem? [tracker_udp.cc#L148](https://github.com/rakshasa/libtorrent/blob/4d305e387a6131c94b87c20595429389a3c55c02/src/tracker/tracker_udp.cc#L148)

B. It breaks this setup: [DHT not enabled. even when it is](https://github.com/rakshasa/rtorrent/issues/383#issuecomment-247645735)
Error message: `Scheduled command failed: dht_node: DHT not enabled.`

**Comment by rakshasa** [comment]
Working on this atm.

**Comment by chros73** [comment]
Thank You! :)

**Comment by chros73** [comment]
Btw, what do you think about this potential issue: [IPv6 Peer Flood](https://torrentfreak.com/popular-torrents-being-sabotaged-by-ipv6-peer-flood-150619/) and a [possible fix](https://forum.utorrent.com/topic/99657-ip6-peer-flood-mitigations-and-some-possible-fixes/) of it?

**Comment by rakshasa** [comment]
Try the fix-udp-trackers branch.

**Comment by chros73** [comment]
After a quick test:
- point A. is fixed :)
- point B. is not: DHT is broken completely (same linked config works fine with 0.9.6/0.13.6)
Cheers

**Comment by rakshasa** [comment]
Try the fix-dht branches for both projects. If there are issues use the new 'dht_all' logging group.

**Comment by chros73** [comment]
Thanks, B. is also solved now. :)
