### ISSUE TITLE
How to compile the project and use it?

### ISSUE THREAD

**Issue by WuYiP** [rakshasa/libtorrent#132]
Dear author, I am a beginner,I want to use the project,I read the "https://github.com/rakshasa/libtorrent/blob/master/INSTALL",at the same time ,I use the profile(/libtorrent/INSTALL) to compile the /libtorrent/src,But now,I could not make it.Therefore ,I need your help ,can you take me some suggestions?Thank you!

**Comment by rakshasa** [comment]
Issue tracker is not a support forum.
