### ISSUE TITLE
Create a search only through the BitTorrent network

### ISSUE THREAD

**Issue by korenevskiy** [rakshasa/libtorrent#136]
Creating a search without a server, search downloads through the hash.
For example: If the title(name) of any download calculate the hash, then you can search without trackers, you can look directly into the network by UDP.
How it works: Everyone who creates seed should input the naming of 3-5 titles, each of which will be determined by the hash. These hashes are to be assigned to the seed. Example hashes for the titles: "Terminator", "Terminator 2", "Терминатор", "Терминатор 2".
When searched, it must be performed to compare and contrast hashes seeds. Example: when searching display a list of all the names that have a only one certain desired hash, ie in the table are displayed when searching for a different distribution of the hash (which is defined by its name), each line is a separate distribution of torrents.
.
The result is a search engine that is not possible to block on any tracker. None of the copyright.
.
And of course it is obvious that this is a very complex function.
But the meaning of it is that if it is. It client will not be just the same as everyone. It client will be at 4 heads above all the clients together.
A very large popularity.
.
The creation of such a function is similar to the invention Bitcoins.

**Comment by rakshasa** [comment]
Out of scope of this project.
