### ISSUE TITLE
rtorrent doesn't apply network.port_range settings in feature_bind

### ISSUE THREAD

**Issue by joke-junkie** [rakshasa/libtorrent#146]
I imagine this
`bind_struct`
`make_bind_struct(const sockaddr* sa, int flags, uint16_t priority) {`
`  return bind_struct { flags, prepare_sockaddr(sa, flags), priority, 6980, 6999 };
}`
piece of code constructing itr there
`for (auto& itr : *this) {`
`    int fd = attempt_listen(itr, backlog, listen_fd);`
in src/torrent/net/bind_manager.cc causes the issue.

I understand it's a temporary solution, but when it will be fixed ?

**Comment by perfect7gentleman** [comment]
confirm

**Comment by Zucht** [comment]
Is it fixed 45eed00125439c2b1b0d0d29c28d37833af038d1?

**Comment by perfect7gentleman** [comment]
yes, fixed
