### ISSUE TITLE
 Huge log files in the home folder

### ISSUE THREAD

**Issue by andoruB** [rakshasa/libtorrent#154]
Initially asked this on [qBittorrent's git repo](https://github.com/qbittorrent/qBittorrent/issues/6937), but I was told it is a libtorrent issue, so I copied the issue here too.

I get quite large log files whenever I run qBittorrent in my home folder, I've even seen some of them get as big as a few GiB.
The files in question: disk_access.log, disk_buffers.log, disk_io_thread.log and (the larger of all 4) buffer_stats.log
There's also a "session_stats" folder that I've tried to prevent from being created by linking it to /dev/null, but all that did is to inflate my ~/.xsession-errors...
Is there any way to disable these useless logs from taking up space and causing excessive disk writing?
I've tried changing various settings under Advanced, but nothing seems to rid me of the logs...

I've tried compiling libtorrent through Debian's official way (apt-get source), and added --disable-debug when configuring (rules file) and after that I recompiled qBittorrent, but those logs still show up...

**Comment by chros73** [comment]
Isn't qBittorent uses the [other libtorrent](https://github.com/arvidn/libtorrent) project?

**Comment by andoruB** [comment]
Whoops! Didn't pay close attention to the repo description... Sorry about that.
