### ISSUE TITLE
pre-packed libtorrent 0.13.7 missing OpenSSL 1.1.0 support

### ISSUE THREAD

**Issue by Zucht** [rakshasa/libtorrent#172]
When compiling pre-packed libtorrent-0.13.4.tar.gz file from GitHub or rtorrent.net/downloads with OpenSSL 1.1.0 it fails. See issue [https://github.com/rakshasa/libtorrent/issues/138](url)

**Comment by chros73** [comment]
Duplicate: https://github.com/rakshasa/rtorrent/issues/730
