### ISSUE TITLE
rtorrent / libtorrent build error

### ISSUE THREAD

**Issue by rezso** [rakshasa/libtorrent#177]
If I try to compile rtorrent 0.9.6 with libtorrent 0.13.7, the build fails:
https://gist.github.com/rezso/6e9419d0249a04296be63c28fb95b9e9

I think, these errors comes from libtorrent.

**Comment by rakshasa** [comment]
See if lt_tr1_functional is defined in config.h.

**Comment by chros73** [comment]
@rezso: don't mix different versions together, especially not these 2!
Use:
- 0.9.6 with 0.13.6
- or 0.9.7 with 0.13.7

**Comment by rezso** [comment]
@chros73: thank you, I can compile 0.9.7 with 0.13.7.
