### ISSUE TITLE
[v0.13.7] Command "system.file_allocate.set" does not exist

### ISSUE THREAD

**Issue by pgera** [rakshasa/libtorrent#178]
OS: RHEL 7
libtorrent config: ./configure --with-posix-fallocate
rtorrent config: ./configure --with-xmlrpc-c --enable-ipv6
File system: lvm-thin + xfs

This option works with older versions of libtorrent/rtorrent on the same system

**Comment by chros73** [comment]
It's called `system.file.allocate.set` now (and it belongs to rtorrent not libtorrent).

**Comment by pgera** [comment]
Thanks. Changing system.**file_allocate**.set to system.**file.allocate**.set solved it. No error on launch. My .rtorrent.rc was pretty old, and was using the older convention.

**Comment by chros73** [comment]
Do you want to set it to `1`? If so, it won't work: https://github.com/rakshasa/libtorrent/pull/152

**Comment by pgera** [comment]
Yes, I wanted to set it to 1 (which is what it was in my old config). Is this a new change in 0.13.7 ? Or does 0.13.6 also have the same issues ?

**Comment by chros73** [comment]
Actually it was worse in v0.13.6 (it randomly applied the behavior of both `0` and `1`), in v0.13.7 it always applies `0` no matter you set.
You can try to compile [rtorrent-ps-ch](https://github.com/chros73/rtorrent-ps-ch) to try out the above mentioned [partial fix](https://github.com/chros73/rtorrent-ps-ch/issues/68).
