### ISSUE TITLE
recipe for target 'diffie_hellman.lo' failed

### ISSUE THREAD

**Issue by champsilva** [rakshasa/libtorrent#188]
> 
> Makefile:424: recipe for target 'diffie_hellman.lo' failed
> make[3]: *** [diffie_hellman.lo] Error 1
> make[3]: *** Waiting for unfinished jobs....
> mv -f .deps/instrumentation.Tpo .deps/instrumentation.Plo
> make[3]: Leaving directory '/tmp/libtorrent-0.13.6/src/utils'
> Makefile:573: recipe for target 'all-recursive' failed
> make[2]: *** [all-recursive] Error 1
> make[2]: Leaving directory '/tmp/libtorrent-0.13.6/src'
> Makefile:505: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/tmp/libtorrent-0.13.6'
> Makefile:414: recipe for target 'all' failed
> make: *** [all] Error 2

I'm getting this erro, i saw some reated issues and i need to patch, but how can i patch? Is there any step by step tutorial? 

Thanks in advanced. 

Im running debian 9.

**Comment by rakshasa** [comment]
Ususally the error happens earlier, post more than just the last bits of the build logs.

**Comment by champsilva** [comment]
> Ususally the error happens earlier, post more than just the last bits of the build logs.

https://pastebin.com/C4k6DHMY

I pasted here

Thanks for the answer

**Comment by chros73** [comment]
Or you can try to build / run [rtorrent-ps](https://github.com/pyroscope/rtorrent-ps) or [rtorrent-ps-ch](https://github.com/chros73/rtorrent-ps-ch) .

**Comment by rakshasa** [comment]
It might be some changes in openssl's headers, what version do you have installed?

**Comment by johnchoi8** [comment]
This still happens with the .tar.gz at http://rtorrent.net/downloads/ still too. Can we get libtorrent-0.13.7.tar.gz updated on the download site? Thanks!

**Comment by champsilva** [comment]
> It might be some changes in openssl's headers, what version do you have installed?

latest

**Comment by kogoromori** [comment]
Having the same problem. Is there already any solution for?

**Comment by rakshasa** [comment]
Try the current HEAD.

**Comment by kogoromori** [comment]
rtorrent 0.9.8 and libtorrent 0.13.8 did it for me.
thanks.
