### ISSUE TITLE
libtorrent: FTBFS on hurd-i386: error: 'IPV6_TCLASS' was not declared in this scope.

### ISSUE THREAD

**Issue by hahawang-github** [rakshasa/libtorrent#219]
I decide to fix a broken package found at the recommended
page(https://people.debian.org/~sthibault/out_of_date.txt) named `libtorrent`.

After I downloaded the package source and tried to build without any modifications under the debian hurd running in qemu (debian-hurd-20210219.img), I got the following error.

```
   socket_fd.cc: In member function 'bool torrent::SocketFd::set_priority(torrent::SocketFd::priority_type)':
   socket_fd.cc:78:43: error: 'IPV6_TCLASS' was not declared in this scope; did you mean 'IPOPT_CLASS'?
```

To fix this bug, thanks to the help of people at debian-hurd & bug-hurd mailing list,  I decide to block the usage of the `IPV6_TCLASS` when it is not defined.

A pull request is available.

The gnu hurd mailing list, that already contains a submitted patch and other people's reviews.

https://lists.gnu.org/archive/html/bug-hurd/2021-04/msg00080.html

**Comment by rakshasa** [comment]
Closing, see PR.
