### ISSUE TITLE
Replace legacy sync* builtins with modern atomic* builtins: fixes build on 32-bit platforms

### ISSUE THREAD

**Issue by barracuda156** [rakshasa/libtorrent#253]
@rakshasa Could you please take a look?

The issue is that old `sync*` builtins require 8-byte atomics support in hardware. That leaves 32-bit platforms (arm, ppc, mips) broken. What will work for both 64- and 32-bit platforms alike is usage of modern `atomic*` builtins. 32-bit archs will just need an explicit linking to `libatomic`.

This a patch which is confirmed to fix compilation on `ppc`, but maybe you can suggest a better solution or verify/improve upon this one?

https://github.com/macports/macports-ports/blob/4ac3291874cad2051b9cc1ba08cadd62643f92f5/net/libtorrent-devel/files/0001-Fix-atomics-for-modern-gcc.patch

**Comment by stickz** [comment]
@barracuda156 Could you submit a pull request for this patch? I'd like to take responsibility for testing this change and getting it incorporated into the project. I'll request a review from @rakshasa when the time is right and get it merged for you.

**Comment by rakshasa** [comment]
I'd rather replace them with `std::atomic`, as that will avoid any compiler dependency.

**Comment by barracuda156** [comment]
@stickz Sorry, I am away from the testing hardware at the moment, so can’t do much until I am back.

@rakshasa If you can handle this, it will be much better, since I am not too sure that my fix is the right one.

(FWIW, we will still depend on `libatomic` on some 32-bit archs, AFAIU, as long as 8-byte atomics is needed in some form.)

**Comment by rakshasa** [comment]
All `__sync_` calls removed, so `libatomic` should no longer be required.

**Comment by barracuda156** [comment]
@rakshasa Thank you very much, I will try it out.

**Comment by barracuda156** [comment]
@rakshasa Everything compiles fine now for me, thanks again.
