### ISSUE TITLE
libtorrent fails to compile using clang with libc++

### ISSUE THREAD

**Issue by mistydemeo** [rakshasa/libtorrent#47]
libtorrent fails to compile with clang when clang is using libc++ as its C++ stdlib (for example, on Mac OS X 10.9 where that is the default). The failure comes from libtorrent using the TR1 prefixed versions of a few headers; libc++ includes only the C++11 versions of these, not the TR1 versions.

You can see the build logs here: https://gist.github.com/mistydemeo/7271614 I also notice that configure says:

> checking for C++11 support... no

Which isn't correct. Seems to come from this in the configure test for C++11 support:

```
conftest.cpp:32:24: error: union member 'b1' has a non-trivial copy constructor
union test { Bar b1; };
^
/Library/Developer/CommandLineTools/usr/bin/../lib/c++/v1/unordered_map:733:5: note: because type 'std::__1::unordered_map<Foo *, int, std::__1::hash<Foo *>, std::__1::equal_to<Foo *>, std::__1::allocator<std::__1::pair<Foo *const, int> > >' has a user-provided copy constructor
unordered_map(const unordered_map& __u);
^
1 error generated.
```

**Comment by bapzangbo** [comment]
Undefined symbols for architecture i386:
  "libtorrent::absolutetime_deprecated_()", referenced from:
      libtorrent::session::session(libtorrent::fingerprint const&, int, unsigned int) in main.o
  "libtorrent::session::init(std::__1::pair<int, int>, char const*, libtorrent::fingerprint const&, unsigned int)", referenced from:
      libtorrent::session::session(libtorrent::fingerprint const&, int, unsigned int) in main.o
  "libtorrent::session::start(int)", referenced from:
      libtorrent::session::session(libtorrent::fingerprint const&, int, unsigned int) in main.o
  "libtorrent::session::~session()", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rweichler** [comment]
It appears that there is a regression. I'm getting the same error as @andyattebery.

**Comment by rweichler** [comment]
It appears there has been a regression.

```
clang++ -DHAVE_CONFIG_H -I. -I../.. -I. -I./.. -I../..    -Wno-deprecated-declarations -O3 -std=c++11 -stdlib=libc++ -g -DDEBUG -D_THREAD_SAFE -pthread  -I/usr/local/Cellar/libsigc++/2.10.0/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.10.0/lib/sigc++-2.0/include  -I/usr/local/Cellar/libtorrent/0.13.6/include -MT curl_get.o -MD -MP -MF .deps/curl_get.Tpo -c -o curl_get.o curl_get.cc
In file included from curl_get.cc:44:
In file included from ./../globals.h:41:
../../rak/priority_queue_default.h:41:10: fatal error: 'tr1/functional' file not found
#include <tr1/functional>
```

I used the following commands to build:
```
CC=clang CXX=clang++ CXXFLAGS="-Wno-deprecated-declarations -O3 -std=c++11 -stdlib=libc++" ./configure
make
```
