### ISSUE TITLE
show why bencoded data could not be parsed

### ISSUE THREAD

**Issue by arekm** [rakshasa/libtorrent#64]
Could raw string (maybe sanitized or only 10-20 characters of it) received from server be shown in case of bencoded data parsing failure?

Something like this:
http://git.pld-linux.org/gitweb.cgi?p=packages/libtorrent.git;a=blob_plain;f=libtorrent-bencoded-error.patch;hb=HEAD

**Comment by Speeddymon** [comment]
This would be nice!
