### ISSUE TITLE
Force Stop Seeding

### ISSUE THREAD

**Issue by gayanhewa** [rakshasa/libtorrent#73]
I am working with libtorrent python binding write a script that downloads torrents files from the url. I was trying to locate the parameters that allows me to limit seeding ( ie. upload at 0 kbps or completely stop seeding ). 

Any direction would be appreciated.

**Comment by remram44** [comment]
Are you sure you are not using [rasterbar's libtorrent](http://www.rasterbar.com/products/libtorrent/)? It's a separate project from this one.
