### ISSUE TITLE
transmission-gtk compatibility problem

### ISSUE THREAD

**Issue by mikefaille** [rakshasa/libtorrent#77]
I make my own torrent on my server with :
mktorrent -a udp://open.demonii.com:1337 flynn-base-disk1.vmdk

After, in same folder, I try to serve this torrent with : 
rtorrent flynn-base-disk1.vmdk.torrent

But, on my client,  transmission isn't able to download this file. And, I can with ktorrent.

**Comment by mikefaille** [comment]
Note : I use rtorrent from centos 7 epel.

```
Name        : rtorrent
Arch        : x86_64
Version     : 0.9.4
Release     : 2.el7
```
```
Name        : libtorrent
Arch        : x86_64
Version     : 0.13.4
Release     : 2.el7
```

**Comment by rakshasa** [comment]
Assuming this is an uTP-not-implemented issue.
