### ISSUE TITLE
Not updated "configure.ac" file in 0.13.5 release...

### ISSUE THREAD

**Issue by Micdu70** [rakshasa/libtorrent#82]
Hello, the 0.13.5 release ( https://github.com/rakshasa/libtorrent/releases/tag/0.13.5 ) has the 0.13.4 version of "configure.ac" file.
It causes rtorrent 0.9.5 to not configure, as it finds libtorrent 0.13.4 instead of 0.13.5.
^^

**Comment by justinkb** [comment]
Confirming this issue

**Comment by eskildsf** [comment]
To fix run "sed -i 's/0.13.4/0.13.5/g' configure"

**Comment by Micdu70** [comment]
@eskildsf There is already an updated configure.ac file in the "branch-0.13.5" release, but it was not merged into the "0.13.5" release => https://github.com/rakshasa/libtorrent/commit/a7857b2a9d047499707d3cd97eaed7e59599d5a2

;)

**Comment by zk1234** [comment]
Confirming this issue. As a result, there is also a problem to compile the newest rtorrent binary (because  it claims that the rtorrent library is too old).

**Comment by rdpse** [comment]
Just use https://github.com/rakshasa/libtorrent/archive/branch-0.13.5.tar.gz

**Comment by pyroscope** [comment]
Unless the ABI actually didn't change, then `LIBTORRENT_CURRENT` is still in need of a bump.

**Comment by rakshasa** [comment]
0.13.5 was a bad attempt at using github for releases.

Check out http://rtorrent.net/downloads/ instead.
