### ISSUE TITLE
Got 203 no transaction id on libtorrent peer

### ISSUE THREAD

**Issue by spin6lock** [rakshasa/libtorrent#88]
Hi, I'm writting a simple DHT crawler now. And I've gotten many "203 no transaction id" from libtorrent peer. My request is like this:

```
'd1:y1:q1:q9:find_node1:t2:\x00\t1:ad2:id20:#\xbfc\x02>\xbc\xc0.\xc6+\x94\xb0#61\xdd\x8d\xd68a6:target20:\x0b\xf5?\xda\x1f\xfd\x80\x08\xef@\xd5\xa5\xdec\xf1,\xf7?\x9f3ee'
```

"1:t2:\x00\t" is the transaction id for DHT query. 1:t represents "t", and "2:\x00\t" represents "\x00\t" string.  I can't figure out why libtorrent keep telling me "no transaction id". Could you help me, please?

**Comment by RealAlexJones** [comment]
libTorrent is picky about the order of keys in some of the bencode that it parses ( ones that go through static_map_read_bencode_c ) 

Your DHT keys are out of order so this function ends early not seeing that there are other valid keys. 

For the order in which keys need to be take a look at https://github.com/rakshasa/libtorrent/blob/master/src/dht/dht_server.cc DhtMessage::key_list_type DhtMessage::base_type::keys 

```
d1:ad2:id20:#AAAAAAAAAAAAAAAAAAAe1:q9:find_node1:t2:AA1:y1:qe
```
Is an example of the query that you're attempting that libTorrent parses correctly.

**Comment by spin6lock** [comment]
@RealAlexJones Thanks a lot! It's very helpful, especially the quote of the spec :)
