### ISSUE TITLE
would it be a true simple

### ISSUE THREAD

**Issue by lilothar** [rakshasa/libtorrent#95]
I found the simple_client would not fit current version, your code read good, but some do not know much about the lib, will hardly to ge start with it, so I suggest it make a example dir and give some examples for good

**Comment by pyroscope** [comment]
https://github.com/rakshasa/rtorrent has lots of examples.

**Comment by rakshasa** [comment]
The complexity of the library and it's interactions with the client is too much for me to document / write code at this moment.

However the simple client should be enough to make it work as long as you deal with the API changes.
