### ISSUE TITLE
does it need sigc++

### ISSUE THREAD

**Issue by lilothar** [rakshasa/libtorrent#96]
I inspect the some feathure of sigc++, I thing it is not nessary to using it, sinece gcc supports cxx0x, tr1::function and bind and c++11 function and bind will solve the problem smart, for users, it will be glad to hear that they need not to install dependency libs, it does easy to install and using, for only to learn std lib

**Comment by rakshasa** [comment]
It is not used.

**Comment by lilothar** [comment]
maybe ,I will rewrite a new branch nodependecy just stdc++ origin your work
